<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Generate XML documentation file for API documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn> <!-- Ignore missing XML comment warnings -->
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScannerService.Domain\ScannerService.Domain.csproj" />
  </ItemGroup>
</Project>
